version: '3.1'

services:
  admin-panel:
    image: ghcr.io/microservisler/admin-panel:latest
    ports:
      - "3460:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
